# reload config file (change file location to your the tmux.conf you want to use)
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# correct colors for themes
set -g default-terminal 'tmux-256color'
set -ag terminal-overrides ',alacritty:RGB'

# 1 based indexing
set -g base-index 1
set -g renumber-windows on

# scrollback
set -g history-limit 10000

#?
set -g terminal-overrides 'xterm*:smcup@:rmcup@'

# fix tmux panes inside docker: ?
set -ag terminal-overrides ',*:enacs@:smacs@:rmacs@:acsc@'
set -ag terminal-overrides ',*:cud1=\E[1B'

# rebind pane selection keys, get rid of infuriating "repeat"
set -g mouse off
set -g repeat-time 0

# split window to same directory
unbind '"'
unbind '%'
bind '\' split-window -c "#{pane_current_path}"
bind '|' split-window -h -c "#{pane_current_path}"

# vi
set -g status-keys vi
set -g bell-action any
set -g mode-keys vi
set -g focus-events on

# graphical-terminal title
set -g set-titles on

## clock
set -g status-right '%Y-%m-%d %H:%M '
set -g status-right-length 50

# faster commands
set -s escape-time 50

# resize
set -g aggressive-resize on

# dont auto rename
set -g allow-rename off

# Open popup-shell
unbind ?
bind ? display-popup -w 80% -h 80% -E 'tmux list-keys -N | less'
bind C-r display-popup -w 80% -h 60% -d '#{pane_current_path}' -E '/bin/bash'

# default colors
set -g window-status-current-style bg=black,fg=white
set -g pane-active-border-style fg=green,bg=black
set -g pane-border-style fg=white,bg=black
set -g message-style fg=black,bg=green


# fix home/end keys (for when tmux is setting $TERM to xterm-256color)
#bind-key -n Home send Escape "OH"
#bind-key -n End send Escape "OF"

# graphical-terminal title
set -g set-titles on
set -g set-titles-string   '#S:#W #{pane_current_command} #{pane_current_path}'

# different sizes and bindings for popup displays
unbind-key ?
bind-key ? display-popup -w 75% -h 75% -E 'tmux list-keys -N | less'
bind-key C-r display-popup -w 80% -h 60% -d '#{pane_current_path}' -E '/bin/bash'

